export const products = [
  // Keyboards (1-10)
  {
    id: "prod-001",
    title: "Aura RGB Mechanical Keyboard",
    description: "Premium hot-swappable linear switches with fully customizable per-key RGB lighting and a sleek aluminum frame.",
    price: 149,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.8,
    reviewsCount: 124,
    inStock: true,
  },
  {
    id: "prod-004",
    title: "Ghost White 60% Wireless Keyboard",
    description: "Ultra-compact minimalist design with dual-mode wireless connectivity and long-lasting battery life for clean desk setups.",
    price: 99,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.2,
    reviewsCount: 45,
    inStock: true,
  },
  {
    id: "prod-005",
    title: "Zenith Split Ergonomic Mechanical",
    description: "Advanced split design that promotes a neutral wrist position, featuring tactile switches and programmable macro layers.",
    price: 189,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.7,
    reviewsCount: 32,
    inStock: true,
  },
  {
    id: "prod-006",
    title: "Retro-Luxe Typewriter Keyboard",
    description: "Modern mechanical performance meets vintage aesthetics with satisfying clicky switches and round chrome-accented keycaps.",
    price: 125,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.4,
    reviewsCount: 67,
    inStock: true,
  },
  {
    id: "prod-017",
    title: "MacroCore 17-Key Mechanical Numpad",
    description: "Dedicated mechanical keypad with programmable macro support and PBT keycaps for intense data entry or gaming.",
    price: 55,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1611002226268-6fa87d377488?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.2,
    reviewsCount: 24,
    inStock: true,
  },
  {
    id: "prod-021",
    title: "CyberPulse TKL Mechanical Keyboard",
    description: "Compact tenkeyless layout with clicky blue switches, durable double-shot PBT caps, and customizable RGB paths.",
    price: 119,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.6,
    reviewsCount: 92,
    inStock: true,
  },
  {
    id: "prod-022",
    title: "NovaQuiet Membrane Slim Keyboard",
    description: "Whisper-quiet low profile keys with a full-size layout and spill-resistant design perfect for daily tasks.",
    price: 39,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.3,
    reviewsCount: 145,
    inStock: true,
  },
  {
    id: "prod-023",
    title: "CarbonPro Custom DIY Keyboard Kit",
    description: "Enthusiast hot-swap barebone kit featuring a CNC machined aluminum case, brass plate, and dampening foam layers.",
    price: 199,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1626958390898-162d3577f593?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.9,
    reviewsCount: 18,
    inStock: true,
  },
  {
    id: "prod-024",
    title: "Atlas Wireless Multi-Device Board",
    description: "Sleek multi-device Bluetooth keyboard that pairs with up to 3 devices simultaneously, built-in tablet cradle.",
    price: 79,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.4,
    reviewsCount: 56,
    inStock: true,
  },
  {
    id: "prod-025",
    title: "Stealth Strike Low Profile Keyboard",
    description: "Ultra-thin mechanical switches with lightning-fast actuation and dynamic per-key backlight zones.",
    price: 139,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.5,
    reviewsCount: 74,
    inStock: true,
  },

  // Keyboards (11-20)
  {
    id: "prod-026",
    title: "Vortex 75% Compact Mechanical",
    description: "A space-saving 75% form factor layout with tactile brown switches and full pre-lubed stabilizers.",
    price: 109,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=400",
    badge: "Top Rated",
    rating: 4.7,
    reviewsCount: 41,
    inStock: true,
  },
  {
    id: "prod-027",
    title: "Eclipse Solar Wireless Keyboard",
    description: "Eco-friendly solar-powered thin keyboard that charges in any light environment, offering months of use in total darkness.",
    price: 89,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.2,
    reviewsCount: 112,
    inStock: true,
  },
  {
    id: "prod-028",
    title: "GamerX Core RGB Keyboard",
    description: "Entry-level gaming keyboard with reactive zone backlighting, 19-key anti-ghosting, and dedicated multimedia dials.",
    price: 49,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.1,
    reviewsCount: 215,
    inStock: true,
  },
  {
    id: "prod-029",
    title: "ProFit Split Ergonomic Board",
    description: "Contoured split key layout with fixed wrist cushions to optimize posture and eliminate muscle strains.",
    price: 159,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.6,
    reviewsCount: 38,
    inStock: true,
  },
  {
    id: "prod-030",
    title: "Foundry Industrial Heavy Board",
    description: "Rugged dustproof mechanical keyboard enclosed in structural steel frame designed for harsh manufacturing lines.",
    price: 175,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1611002226268-6fa87d377488?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.8,
    reviewsCount: 14,
    inStock: true,
  },
  {
    id: "prod-074",
    title: "Nebula 65% Walnut Mechanical Keyboard",
    description: "Stunning solid walnut hardwood housing built with hot-swap sockets, linear yellow silent switches, and retro cream keycaps.",
    price: 165,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.8,
    reviewsCount: 64,
    inStock: true,
  },
  {
    id: "prod-075",
    title: "HydroFlow Spill-Proof Board",
    description: "Full-sized office structural build featuring defensive internal routing channels capable of brushing away deep accidents instantly.",
    price: 42,
    category: "keyboard",
    image: "https://images.unsplash.com/photo-1626958390898-162d3577f593?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.2,
    reviewsCount: 105,
    inStock: true,
  },

  // Mice (1-10)
  {
    id: "prod-002",
    title: "PrecisionPro Wireless Mouse",
    description: "High-performance productivity mouse with a 26k DPI sensor, infinite scroll wheel, and ergonomic thumb rest.",
    price: 89,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.5,
    reviewsCount: 88,
    inStock: true,
  },
  {
    id: "prod-007",
    title: "SwiftGlide Ultra-Light Gaming Mouse",
    description: "Engineered for speed with a 55g honeycombed shell, PTFE feet, and a zero-latency optical sensor.",
    price: 75,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=400",
    badge: "Pro",
    rating: 4.9,
    reviewsCount: 156,
    inStock: true,
  },
  {
    id: "prod-008",
    title: "QuietCore Silent Office Mouse",
    description: "Reduced-noise switches that provide a satisfying tactile feel without the loud click, ideal for quiet office environments.",
    price: 45,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1613141411244-0e4ac259d217?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.1,
    reviewsCount: 230,
    inStock: true,
  },
  {
    id: "prod-016",
    title: "Orthopedic Vertical Ergo Mouse",
    description: "Scientifically designed vertical mouse that reduces forearm twisting and muscle strain during long work days.",
    price: 59,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1527814732941-43b379c84144?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.3,
    reviewsCount: 110,
    inStock: true,
  },
  {
    id: "prod-031",
    title: "ApexStrike RGB Wireless Gaming Mouse",
    description: "Next-gen ultra lightweight frame, 30K optical focus sensor, and hyper-responsive optical mouse switches.",
    price: 129,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.9,
    reviewsCount: 164,
    inStock: true,
  },
  {
    id: "prod-032",
    title: "ErgoGlide Vertical Wireless Mouse",
    description: "Ergonomically engineered 57-degree vertical handshake grip to decrease wrist fatigue and forearm pressure.",
    price: 65,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1527814732941-43b379c84144?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.5,
    reviewsCount: 83,
    inStock: true,
  },
  {
    id: "prod-033",
    title: "Nomad Compact Travel Bluetooth Mouse",
    description: "Pocket-sized wireless mouse with a collapsible flat shape and magnetic scroll wheel for seamless portability.",
    price: 39,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.2,
    reviewsCount: 198,
    inStock: true,
  },
  {
    id: "prod-034",
    title: "OfficeFlow Multi-Device Laser Mouse",
    description: "Precision tracking on glass surfaces with full multi-device cross-computer control and dual scroll mechanisms.",
    price: 95,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1613141411244-0e4ac259d217?auto=format&fit=crop&q=80&w=400",
    badge: "Top Rated",
    rating: 4.7,
    reviewsCount: 122,
    inStock: true,
  },
  {
    id: "prod-035",
    title: "HyperSpeed Wired Gaming Mouse",
    description: "62g wired gaming icon featuring high-flex paracord cable, pure PTFE skates, and crisp 80M rated clicks.",
    price: 59,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.4,
    reviewsCount: 340,
    inStock: true,
  },
  {
    id: "prod-036",
    title: "Valor Trackball Ergonomic Mouse",
    description: "Stationary sculpting design with precise thumb-controlled smooth trackball and adjustable tilt hinge platforms.",
    price: 85,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1527814732941-43b379c84144?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.3,
    reviewsCount: 73,
    inStock: true,
  },

  // Mice (11-13) & Audio (1-7)
  {
    id: "prod-037",
    title: "AeroMesh Honeycomb Wired Mouse",
    description: "Breathable shell architecture containing an adjustable internal weight cartridge system and custom lighting scripts.",
    price: 49,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.4,
    reviewsCount: 52,
    inStock: true,
  },
  {
    id: "prod-038",
    title: "TitanClick Heavy Duty Office Mouse",
    description: "Durable construction designed to endure over 100 million activations, complete with a braided nylon connector.",
    price: 34,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.1,
    reviewsCount: 119,
    inStock: true,
  },
  {
    id: "prod-039",
    title: "ProDraw Wireless Stylus Mouse",
    description: "Hybrid pen-shaped mouse tailored for digital sketch artists, architects, and detail-oriented photo retouchers.",
    price: 110,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1613141411244-0e4ac259d217?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.6,
    reviewsCount: 29,
    inStock: true,
  },
  {
    id: "prod-076",
    title: "ShadowStrike Wireless MMO Mouse",
    description: "Ergonomic multi-button setup layout offering 12 fully programmable side-thumb macro keys for intense game configurations.",
    price: 105,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1625842268584-8f3290466a41?auto=format&fit=crop&q=80&w=400",
    badge: "Top Rated",
    rating: 4.7,
    reviewsCount: 89,
    inStock: true,
  },
  {
    id: "prod-077",
    title: "AeroTouch Magnesium Wireless Mouse",
    description: "Exquisite skeletal layout constructed from ultra-durable magnesium alloy, bringing operational weights down to a pure 49 grams.",
    price: 145,
    category: "mouse",
    image: "https://images.unsplash.com/photo-1683483424143-6901c569f6e6?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.9,
    reviewsCount: 22,
    inStock: true,
  },
  {
    id: "prod-003",
    title: "HifiOne Studio ANC Headphones",
    description: "Premium over-ear headphones featuring adaptive noise cancellation and studio-grade spatial audio drivers.",
    price: 249,
    category: "audio",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.9,
    reviewsCount: 210,
    inStock: false,
  },
  {
    id: "prod-009",
    title: "SonarPulse 7.1 Surround Gaming Headset",
    description: "Immersive 7.1 surround sound with a noise-canceling broadcast-quality microphone and memory foam ear cushions.",
    price: 135,
    category: "audio",
    image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=400",
    badge: "Top Rated",
    rating: 4.6,
    reviewsCount: 95,
    inStock: true,
  },
  {
    id: "prod-010",
    title: "SonicBuds Pro True Wireless Earbuds",
    description: "Compact wireless earbuds with active noise cancellation, sweat resistance, and up to 30 hours of total battery life.",
    price: 69,
    category: "audio",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.3,
    reviewsCount: 312,
    inStock: true,
  },
  {
    id: "prod-018",
    title: "AudioEdge 2.0 Hi-Fi Desktop Speakers",
    description: "High-fidelity bookshelf speakers with balanced acoustics, deep bass response, and elegant wood-grain finish.",
    price: 85,
    category: "audio",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.5,
    reviewsCount: 76,
    inStock: true,
  },
  {
    id: "prod-040",
    title: "StudioWave Open-Back Reference Headphones",
    description: "Audiophile-grade open-back design providing incredibly transparent acoustics and realistic sound staging grids.",
    price: 299,
    category: "audio",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400",
    badge: "Premium",
    rating: 4.9,
    reviewsCount: 65,
    inStock: true,
  },

  // Audio (8-15)
  {
    id: "prod-041",
    title: "PulseBuds Sport True Wireless",
    description: "Secure-fit ear hooks with sweat-guard nano coating and ambient awareness safety modes for runner workouts.",
    price: 79,
    category: "audio",
    image: "https://images.unsplash.com/photo-1606220532402-1f600e09d5ee?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.5,
    reviewsCount: 410,
    inStock: true,
  },
  {
    id: "prod-042",
    title: "SoundBarricade Heavy ANC Headset",
    description: "Industrial-strength active noise cancellation blocking up to 40dB of ambient engine humming or loud hums.",
    price: 199,
    category: "audio",
    image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.7,
    reviewsCount: 88,
    inStock: true,
  },
  {
    id: "prod-043",
    title: "VocalStream XLR Condenser Microphone",
    description: "Studio broadcasting microphone featuring a 25mm gold-sputtered diaphragm capsule for rich vocal resonance.",
    price: 149,
    category: "audio",
    image: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&q=80&w=400",
    badge: "Pro",
    rating: 4.8,
    reviewsCount: 51,
    inStock: true,
  },
  {
    id: "prod-044",
    title: "EchoBoom Portable Waterproof Speaker",
    description: "Rugged IP67 dust and waterproof bluetooth soundbox delivering powerful 360-degree deep thumping bass loops.",
    price: 89,
    category: "audio",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.6,
    reviewsCount: 280,
    inStock: true,
  },
  {
    id: "prod-045",
    title: "CinemaSurround Soundbar System",
    description: "Compact multi-driver TV and desktop soundbar with wireless subwoofer and Dolby Digital decoding streams.",
    price: 179,
    category: "audio",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.4,
    reviewsCount: 94,
    inStock: true,
  },
  {
    id: "prod-046",
    title: "Podcaster USB Plug-and-Play Mic",
    description: "Convenient desktop microphone containing an integrated pop filter, zero-latency monitor jack, and mute pad.",
    price: 69,
    category: "audio",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.3,
    reviewsCount: 142,
    inStock: true,
  },
  {
    id: "prod-047",
    title: "AeroBuds Ultra Light Earphones",
    description: "Featherweight canal design weighing only 3.5g per bud, boasting quick charge and ultra clear speech lines.",
    price: 55,
    category: "audio",
    image: "https://images.unsplash.com/photo-1606220532402-1f600e09d5ee?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.2,
    reviewsCount: 115,
    inStock: true,
  },
  {
    id: "prod-048",
    title: "PureAudio DAC Headphone Amplifier",
    description: "High-resolution digital-to-analog converter that extracts absolute fidelity from any digital sound feed.",
    price: 125,
    category: "audio",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.8,
    reviewsCount: 33,
    inStock: true,
  },
  {
    id: "prod-049",
    title: "GameVoice Chat Mixer Pro",
    description: "Tactile hardware control station allowing seamless balancing between game soundtracks and teammate discord lines.",
    price: 99,
    category: "audio",
    image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.5,
    reviewsCount: 62,
    inStock: true,
  },
  {
    id: "prod-078",
    title: "VoxPod Studio Condenser Pack",
    description: "High-fidelity cardioid recording package complete with adjustable articulated arm assembly, shock mount, and woven pop shield lines.",
    price: 155,
    category: "audio",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=400",
    badge: "Premium",
    rating: 4.6,
    reviewsCount: 41,
    inStock: true,
  },
  {
    id: "prod-079",
    title: "PulseWave Wireless Sport Buds",
    description: "IPX7 waterproof rated audio dynamic buds sporting secure wraparound structural grips tailored for high-tempo running loops.",
    price: 75,
    category: "audio",
    image: "https://images.unsplash.com/photo-1606220532402-1f600e09d5ee?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.4,
    reviewsCount: 112,
    inStock: true,
  },

  // Monitors (1-7)
  {
    id: "prod-011",
    title: "VistaCurve 32\" 4K HDR Monitor",
    description: "Stunning 4K resolution with HDR10 support and a 1500R curvature for an immersive gaming and viewing experience.",
    price: 499,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=400",
    badge: "Premium",
    rating: 4.8,
    reviewsCount: 42,
    inStock: true,
  },
  {
    id: "prod-012",
    title: "HorizonWide 34\" Curved Productivity Screen",
    description: "Ultra-wide 21:9 aspect ratio with WQHD resolution, perfect for high-efficiency multitasking and creative workflows.",
    price: 429,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.5,
    reviewsCount: 28,
    inStock: true,
  },
  {
    id: "prod-050",
    title: "HorizonUltra 27\" QHD 165Hz Monitor",
    description: "Fast IPS gaming display featuring crisp 2K resolution, 1ms response latency, and adaptive G-Sync timing.",
    price: 299,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.7,
    reviewsCount: 210,
    inStock: true,
  },
  {
    id: "prod-051",
    title: "PixelPerfect 27\" 4K Colorist Display",
    description: "Professional factory-calibrated monitor with 100% sRGB color spectrum span and convenient USB-C 90W delivery.",
    price: 449,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&q=80&w=400",
    badge: "Premium",
    rating: 4.8,
    reviewsCount: 37,
    inStock: true,
  },
  {
    id: "prod-052",
    title: "TitanWide 49\" Super Ultrawide Display",
    description: "Monstrous 32:9 dual-QHD panoramic workspace screen replacing multiple monitor panels with one single glass canvas.",
    price: 999,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&q=80&w=400",
    badge: "Top Rated",
    rating: 4.9,
    reviewsCount: 15,
    inStock: true,
  },
  {
    id: "prod-053",
    title: "SwiftView 24\" 240Hz Esports Display",
    description: "Competitive gaming display optimizing frame rates via native 240Hz refresh matrices and low-motion blur tools.",
    price: 229,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=400",
    badge: "Pro",
    rating: 4.6,
    reviewsCount: 118,
    inStock: true,
  },
  {
    id: "prod-054",
    title: "FlexPort 15.6\" Portable Monitor",
    description: "Ultra slim travel companion monitor easily powered over a single Type-C link, complete with folding magnetic cover.",
    price: 159,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.4,
    reviewsCount: 85,
    inStock: true,
  },
  {
    id: "prod-055",
    title: "VistaPrime 27\" Business Monitor",
    description: "Comfortable office screen with low blue light filtering filters, height-adjustable column base, and narrow bezels.",
    price: 189,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.3,
    reviewsCount: 93,
    inStock: true,
  },
  {
    id: "prod-056",
    title: "QuantumCurve 45\" OLED Gaming Canvas",
    description: "Breathtaking self-lit OLED panel featuring deep true blacks, infinite contrast ranges, and 240Hz screen fluidity.",
    price: 1299,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 5.0,
    reviewsCount: 8,
    inStock: true,
  },
  {
    id: "prod-080",
    title: "HorizonUltra 32\" 144Hz Gaming Screen",
    description: "Immersive structural 32-inch IPS panel featuring ultra-crisp 1ms step latencies and pristine cinematic color mapping spaces.",
    price: 379,
    category: "monitor",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.8,
    reviewsCount: 76,
    inStock: true,
  },

  // Accessories (1-18)
  {
    id: "prod-013",
    title: "Lumina RGB Extended Desk Mat",
    description: "Massive waterproof surface with 12 customizable RGB lighting modes and a non-slip rubber base.",
    price: 35,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.7,
    reviewsCount: 180,
    inStock: true,
  },
  {
    id: "prod-014",
    title: "TitanFlex Heavy-Duty Monitor Arm",
    description: "Fully adjustable gas spring arm that supports up to 34\" monitors with smooth 360-degree rotation and tilt.",
    price: 79,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1544244015-0cd4b3ff869d?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.6,
    reviewsCount: 54,
    inStock: true,
  },
  {
    id: "prod-015",
    title: "Radiance Pro Streamer Light Kit",
    description: "Professional-grade key light with adjustable color temperature and brightness via integrated controls.",
    price: 115,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1585336139118-89ce3243924f?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.4,
    reviewsCount: 19,
    inStock: true,
  },
  {
    id: "prod-019",
    title: "StreamFocus 1080p HDR Pro Webcam",
    description: "Full HD webcam with HDR support, auto-focus, and a built-in ring light for professional-quality streaming.",
    price: 95,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820bc6988?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.4,
    reviewsCount: 48,
    inStock: true,
  },
  {
    id: "prod-020",
    title: "CloudComfort Premium XL Lap Desk",
    description: "Extra-large lap desk with a breathable dual-bolster cushion and integrated phone slot for ultimate comfort.",
    price: 49,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1603484477859-abe6a73f9366?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.6,
    reviewsCount: 125,
    inStock: true,
  },
  {
    id: "prod-057",
    title: "ShieldPro Waterproof Keyboard Sleeve",
    description: "Form-fitting neoprene transport wrap lined with padded interior pockets for cables and custom artisan caps.",
    price: 25,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1618331812910-001dd3f4aaac?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.4,
    reviewsCount: 42,
    inStock: true,
  },
  {
    id: "prod-058",
    title: "AnchorPoint Under-Desk Headphone Mount",
    description: "Heavy steel dual headset hanger with soft silicone grips, integrated cable organizers, and 360 rotation.",
    price: 19,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1585336139118-89ce3243924f?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.6,
    reviewsCount: 310,
    inStock: true,
  },
  {
    id: "prod-059",
    title: "StreamDeck Pro Macro Control Pad",
    description: "Customizable grid deck with 15 crisp LCD shortcut buttons to execute streaming graphics and application actions.",
    price: 149,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&q=80&w=400",
    badge: "Hot",
    rating: 4.8,
    reviewsCount: 145,
    inStock: true,
  },
  {
    id: "prod-060",
    title: "CableCommander Magnetic Cable Organizers",
    description: "Premium weighted desktop base containing five reusable magnetic cable clips to prevent wire clutter drops.",
    price: 29,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1603484477859-abe6a73f9366?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.5,
    reviewsCount: 275,
    inStock: true,
  },
  {
    id: "prod-061",
    title: "Lumina RGB Laptop Cooling Stand",
    description: "Ergonomic cooling platform equipped with a massive quiet 200mm fan and multi-zone edge illumination striping.",
    price: 45,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1618331812910-001dd3f4aaac?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.3,
    reviewsCount: 168,
    inStock: true,
  },
  {
    id: "prod-062",
    title: "GigaMat 3XL Giant Desk Blotter",
    description: "Enormous micro-woven mousepad covering complete workspace surfaces to shield desk wood from heavy wear.",
    price: 39,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&q=80&w=400",
    badge: "Top Rated",
    rating: 4.7,
    reviewsCount: 194,
    inStock: true,
  },
  {
    id: "prod-063",
    title: "VoltCharge 100W GaN Desktop Charger",
    description: "Pocket-sized multi-port power block featuring advanced gallium nitride chips to safely juice laptops and accessories.",
    price: 69,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820bc6988?auto=format&fit=crop&q=80&w=400",
    badge: "New",
    rating: 4.7,
    reviewsCount: 89,
    inStock: true,
  },
  {
    id: "prod-064",
    title: "AirPurify Compact Desk Ionizer",
    description: "Personal desktop filtration unit eliminating particulate micro-dust and static charges from delicate gear areas.",
    price: 59,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1585336139118-89ce3243924f?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.2,
    reviewsCount: 54,
    inStock: true,
  },
  {
    id: "prod-065",
    title: "AlumaRise Ergonomic Laptop Stand",
    description: "Premium brushed silver aluminum laptop elevator raising screen sightlines to perfect eye-level angles.",
    price: 49,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1603484477859-abe6a73f9366?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.6,
    reviewsCount: 137,
    inStock: true,
  },
  {
    id: "prod-066",
    title: "TravelShell Tech Organizer Pouch",
    description: "Weatherproof hard shell travel case built with mesh webbing dividers to safely bundle drives, adapters, and cards.",
    price: 34,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1618331812910-001dd3f4aaac?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.5,
    reviewsCount: 203,
    inStock: true,
  },
  {
    id: "prod-067",
    title: "GripTape Anti-Slip Mouse Decals",
    description: "Pre-cut textured rubber grip stickers giving players supreme sweat-resistant tactile handling controls.",
    price: 15,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.4,
    reviewsCount: 76,
    inStock: true,
  },
  {
    id: "prod-068",
    title: "SafeGuard Cyber Webcam Shield Set",
    description: "Ultra-thin sliding camera safety shutter plates compatible with laptops, screens, and mobile lenses.",
    price: 12,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820bc6988?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.1,
    reviewsCount: 420,
    inStock: true,
  },
  {
    id: "prod-069",
    title: "NeonGlow Ambient LED Desk Strips",
    description: "Smart sync backing light strips that dynamically illuminate home studio workspaces to matching gaming tempos.",
    price: 29,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1585336139118-89ce3243924f?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.5,
    reviewsCount: 112,
    inStock: true,
  },
  {
    id: "prod-070",
    title: "Titanium Alloy Custom Spacebar",
    description: "Artisan 6.25u spacebar forged from anodized aerospace titanium, presenting a unique heat-treated oil-slick finish.",
    price: 65,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=400",
    badge: "Exclusive",
    rating: 4.9,
    reviewsCount: 17,
    inStock: true,
  },
  {
    id: "prod-071",
    title: "OmniMount Dynamic Dual Arm",
    description: "Heavy-duty aluminum independent gas spring desktop pole setup designed to seamlessly hold up to two 27-inch monitors.",
    price: 129,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1544244015-0cd4b3ff869d?auto=format&fit=crop&q=80&w=400",
    badge: null,
    rating: 4.6,
    reviewsCount: 38,
    inStock: true,
  },
  {
    id: "prod-072",
    title: "VividSpectrum Desk Mat XL",
    description: "Stitch-edged thick desktop protector running an ultra-smooth micro-weave surface optimized for optical tracker precision.",
    price: 32,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&q=80&w=400",
    badge: "Sale",
    rating: 4.4,
    reviewsCount: 149,
    inStock: true,
  },
  {
    id: "prod-073",
    title: "AuraGate Pro MIDI Controller Pad",
    description: "Compact 16-pad USB grid matrix boasting velocity-sensitive action shortcuts designed for lightning fast production workflows.",
    price: 119,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&q=80&w=400",
    badge: "Pro",
    rating: 4.7,
    reviewsCount: 53,
    inStock: true,
  },
];
